application: aretemotion
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img/(.*\.(gif|png|jpg))$
  static_files: img/\1    # assuming you put your images in a directory called 'images'
  upload: img/.*\.(gif|png|jpg)$

- url: /
  script: index.php

- url: /login
  script: login.php

- url: /addcat
  script: categoria_add.php

- url: /delcat
  script: categoria_del.php

- url: /editcat
  script: categoria_edit.php

- url: /savecatname
  script: categoria_save.php

- url: /addset
  script: set_add.php

- url: /listpants
  script: pantallas_list.php